# Generated by Django 6.1.1 on 2026-10-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('stock', models.BigIntegerField(default=1)),
                ('precio', models.DecimalField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(default=1)),
                ('precio_total', models.DecimalField(db_column='precioTotal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('producto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yeezy_back.producto')),
                ('artista', models.TextField()),
                ('duracion', models.BigIntegerField()),
                ('year', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'discos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('producto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yeezy_back.producto')),
                ('talla', models.TextField()),
                ('genero', models.TextField(default='male')),
            ],
            options={
                'db_table': 'ropa',
                'managed': False,
            },
        ),
    ]
